### ISSUE TITLE
Feature: Get list of watched/unwatched episodes from Season or Show

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/python-plexapi#10]
I may be wrong, but currently we can only get them directly from the library:

```python
plex.library.unwatched()
```

**Comment by mjs7231** [comment]
All set. Thanks for the example! I also added watched() and unwatched() convenience methods to the Show and Season classes.

commit 739feffc434725885f51e5c098a06fee1ca1eb6d
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Jun 1 22:55:20 2015 -0400
Get list of watched/unwatched episodes from Season or Show
