### ISSUE TITLE
We should rethink how we use self.isFullObject()

### ISSUE THREAD

**Issue by mjs7231** [mjs7231/python-plexapi#103]
Right now we check if we have a 'full object' and if so, we include extra arguments such as track.mood, or track.media. This is the same for all media types (movies, shows, audio). It seems to the root of quite a few problems from just plain confusion, as well as sometimes costing a big drop in performance if we don't actually want the full object, but we go fetch it anyway. 

Lets use this bug to think of a better solution.

**Comment by Hellowlol** [comment]
I think the parsing should be greedy. We grab as much info as we can on the first go. Reload only happen if that info is missing and the user asks for it. In all other cases the reload should be called by the user.

**Comment by mjs7231** [comment]
That was the idea behind the original implementation and why NA was implemented.  It allows us to know the difference between the None (argument not yet populated) and NA (argument populated but was not available in the XML data). Any other value means the argument was populated and available in the XML data, meaning we don't need to grab the full object. 

What do we do in the case of search results where the first 3 actors are populated, but there may be more if we load the full object page?

**Comment by Hellowlol** [comment]
The user should reload the object.

**Comment by mjs7231** [comment]
Sounds good to me. Only concern is that they may not know they need to reload the object to get the full list because it acts differently for 95% of the other attributes. I have no ideas on how to signal that to the user, maybe there is no clean solution.

**Comment by mjs7231** [comment]
I'm working on this on the remove-na branch. I just removed all references to NA and Travis looks happy, which also makes me very happy, that class was a waste of brain power.  Next I want to dig into reloads and see if we can get that back under control.

**Comment by mjs7231** [comment]
This is covered on the 3.0.0 branch.  All those isFullObject() checks have been removed. :D
