### ISSUE TITLE
Attribute 'unwatched' doesn't exist

### ISSUE THREAD

**Issue by bendews** [mjs7231/python-plexapi#104]
When trying to do the first listed example in the README file, it throws the following exception:
Input:
`for section in plex.library.sections():`
`    print('Unwatched content in %s:' % section.title)`
`    for video in section.unwatched():`
`        print('  %s' % video.title)`

Output:
`AttributeError: 'MovieSection' object has no attribute 'unwatched'`

**Comment by mjs7231** [comment]
Sorry you had a bad first impression. I'll get this fixed shortly.

We're doing a big push to bring this project up to speed with proper testing and documentation in the coming weeks. So that should help this from happening in the future.

**Comment by bendews** [comment]
No problem at all, I've been using it for other functions and it's been great so far, very easy to use. 👍

**Comment by mjs7231** [comment]
Plex removed the internal API we were using to fetch unwatched shows and moved that functionality to the search / filtering a few months back.  I updated the example to reflect this. Thanks for the error report.

```python
# Example 1: List all unwatched movies.
movies = plex.library.section('Movies')
for video in movies.search(unwatched=True):
    print(video.title)
```

**Comment by mjs7231** [comment]
commit b5e29fdb28481b42036fc2451dd96a44211b81a7
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Feb 2 00:49:12 2017 -0500
Fix first example in README

**Comment by bendews** [comment]
Wow what a quick response!! What you mentioned above is working great. Thanks! 😄
