### ISSUE TITLE
Xbox One Support?

### ISSUE THREAD

**Issue by ScottJWhite** [mjs7231/python-plexapi#111]
Does this api support the Xbox One app? I've tried the api on other platforms and it works great. I'm able to find the Xbox client however when you actually attempt to pass content to it the Xbox app doesn't respond.

**Comment by mjs7231** [comment]
Unless we find a dev with an xbox that wants to dig into this one specifically, I don't think we can really answer this. Different devices have different support. I personally only have iPhone, iPad, FireTV, WebClient access myself.

Version 3.0.0 is coming out soon; I'll make sure add a little tool to test client abilities that we can have you and future requests run to help us nail down whats supported where.

**Comment by ScottJWhite** [comment]
Ok, thank you. Great job by the way, it works great otherwise.
