### ISSUE TITLE
getStreamUrl produces a malformed URL

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/python-plexapi#13]
I cant seem to track this bug down, but the URL has an additional `?` mark just before the `X-Plex-Token` paramater (should be an `&`):

```python
plex.library.get('9').getStreamUrl()
```
produces:

```curl
http://localhost:10041/video/:/transcode/universal/start?path=http%3A%2F%2F127.0.0.1%3A32400%2Flibrary%2Fmetadata%2F1450&mediaIndex=0&X-Plex-Platform=Chrome&copyts=1&offset=0?X-Plex-Token=pRcNNDBmZUYkBWdAUaYa
```

Notice the end:

```curl
..&copyts=1&offset=0?X-Plex-Token=pRcNNDBmZUYkBWdAUaYa
```

**Comment by mjs7231** [comment]
This is coming from server.py:107.  Easy fix is to look for ? in the existing url and choose ? or & based on that.

**Comment by mjs7231** [comment]
commit 69e0abd50c9fd1a316d20cb4eafc46c023fba9f0
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Jun 4 10:43:50 2015 -0400
Fix Bug-13 - getStreamUrl produces a malformed URL; Cleanup logging if logfile is not defined
