### ISSUE TITLE
plex.clients() doesn't display any clients

### ISSUE THREAD

**Issue by philipsd6** [mjs7231/python-plexapi#16]
I have the Plex iPhone app connected to my server, and the web app connected, but even while actively streaming to my iPhone, nothing is returned by `plex.clients()`:
```python
In [1]: from plexapi.myplex import MyPlexUser
In [2]: user = MyPlexUser.signin('ME', 'SEKRIT')
In [3]: plex = user.getServer('MyServer').connect()
In [4]: plex.clients()
Out[4]: []
```
Are my expectations incorrect?

**Comment by philipsd6** [comment]
I do see that `plex.sessions()` shows when I'm actually streaming something though:

```python
In [22]: plex.sessions()
Out[22]: [<Episode:Robin.Roberts>]

In [23]: plex.clients()
Out[23]: []
```

Basically, I'm not sure how the `example_004_play_avatar_on_iphone` is supposed to work if I can't get a client instance.

**Comment by mjs7231** [comment]
I'm seeing a similar result when I run it, but I am at my work office. If I remember correctly you need to be on the same network in order to control another client. I'll confirm this tonight when I get home.

**Comment by mjs7231** [comment]
Above comment is correct, your client needs to be on the same network as the Plex server for it to be able to see and control it. The below commit adds a comment explaining this.

commit 5b85a8c829d28dbf37fc77ab2360d94ff246818b
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Jun 8 22:21:31 2015 -0400
Add comment about client being required to be on same server

**Comment by philipsd6** [comment]
OK, understood. Sad though, because since my Plex server is running on a remote headless server, my clients will never be on the same network.
