### ISSUE TITLE
Plex search doesn't work (400) bad_request

### ISSUE THREAD

**Issue by abibouba** [mjs7231/python-plexapi#18]
Hello,

The search example doesn't work. (example #5)
All other examples work really well. Maybe there was an update in the latest Plex server version?

Thanks anyway for this great API :)

**Comment by abibouba** [comment]
Here is the issue:
formatting of the should be http://IP:32400/search?query=game&X-Plex-Token=xxxxxxxxxxx
instead of http://IP:32400/search?query=game?X-Plex-Token=xxxxxxxxxxx

**Comment by mjs7231** [comment]
That's a regression from me adding ssl support. I'll get it fixed today. Sorry about that.

**Comment by mjs7231** [comment]
Also, thanks for finding the cause!

**Comment by mjs7231** [comment]
Example 5 is working for me from the repo.  If you installed plexapi via pip, I'll ask that you wait a few days for me to work a few other things before I update that. -- If you want the repo build (with this issue fixed) you can install with the following command:

pip install git+git://github.com/mjs7231/python-plexapi.git

**Comment by mjs7231** [comment]
I just finished what I wanted to before updating pip.  [Version 1.0.0 is there now](https://pypi.python.org/pypi/PlexAPI/1.0.0), let me know how its working! :D

**Comment by abibouba** [comment]
Thanks for the quick fix :)
I'll let you know in a few hours how it is working.

**Comment by abibouba** [comment]
Now I'm getting this error when trying to connect to the server:

plex = user.getServer('serverName').connect()
AttributeError: MyPlexUser instance has no attribute 'getServer'

**Comment by mjs7231** [comment]
It's getResource() now.

**Comment by abibouba** [comment]
Thanks again :)
Found another issue! 
I will open a new one.
