### ISSUE TITLE
Connecting to main acount from a remote location failed

### ISSUE THREAD

**Issue by abibouba** [mjs7231/python-plexapi#19]
When I try to connect with the user owning the server, it doesn't work.
When I connect with a user who has it as a shared server, it works.
All of this is done from a remote location.

ERROR:plexapi:http://172.x.x.x:32400: HTTPConnectionPool(host='172.x.x.x', port=32400): Max retries exceeded with url: /?X-Plex-Token=(token) (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10a434050>, 'Connection to 172.x.x.x timed out. (connect timeout=5)'))
ERROR:plexapi:https://10-x-x-x.somthg.plex.direct:32400: HTTPSConnectionPool(host='10-x-x-x.somthg.plex.direct', port=32400): Max retries exceeded with url: /?X-Plex-Token=(token) (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10a434250>, 'Connection to 10-x-x-x.somthg.plex.direct timed out. (connect timeout=5)'))
ERROR:plexapi:https://172-x-x-x.somthg.plex.direct:32400: HTTPSConnectionPool(host='172-x-x-x.somthg.plex.direct', port=32400): Max retries exceeded with url: /?X-Plex-Token=(token) (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10a4349d0>, 'Connection to 172-x-x-x.somthg.plex.direct timed out. (connect timeout=5)'))
ERROR:plexapi:http://10.x.x.x:32400: HTTPConnectionPool(host=’10.x.x.x', port=32400): Max retries exceeded with url: /?X-Plex-Token=(token) (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10a434dd0>, 'Connection to 10.90.165.4 timed out. (connect timeout=5)'))
INFO:plexapi:Testing connection: https://172-x-x-x.somthg.plex.direct:32400 ERR
INFO:plexapi:Testing connection: https://10-x-x-x.somthg.plex.direct:32400 ERR
INFO:plexapi:Testing connection: https://62-x-x-x.somthg.plex.direct:32400 OK
INFO:plexapi:Testing connection: http://172.x.x.x:32400 ERR
INFO:plexapi:Testing connection: http://10.x.x.x:32400 ERR
INFO:plexapi:Testing connection: http://62.x.x.x:32400 OK
INFO:plexapi:Connecting to server: None
Traceback (most recent call last):
  File "/Users/myuser/PycharmProjects/PlexCompanion/test1.py", line 12, in <module>
    print movie.checkExisting()
  File "/Users/myuser/PycharmProjects/PlexCompanion/PlexAlert/Movie.py", line 63, in checkExisting
    for video in plex.search(self.name):
AttributeError: 'NoneType' object has no attribute 'search'

**Comment by mjs7231** [comment]
I think I see the problem. I'm not returning the first server that was successful, but just the first server in the list. I'm about to grab dinner, but expect a fix this evening.

**Comment by mjs7231** [comment]
This should fix it. Do you need it in pip?

commit 6b21d856d3db51d5d29c6d15ab0627d129a81d9c
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Jun 15 19:55:12 2015 -0400
Fix for issue #19: Connecting to main acount from a remote location failed

**Comment by mjs7231** [comment]
Its in pip: https://pypi.python.org/pypi/PlexAPI/1.0.1

**Comment by abibouba** [comment]
Thanks again ! It's working perfectly

**Comment by mjs7231** [comment]
Awesome! Thanks for reporting the issues.
