### ISSUE TITLE
Search for id and get data attributes as dict

### ISSUE THREAD

**Issue by Hellowlol** [mjs7231/python-plexapi#2]
the logfile should be made at the same location as teh api or atleast make the dir if it dont exist.

**Comment by simonwjackson** [comment]
+1

**Comment by mjs7231** [comment]
Hellowlol -- This seems like two issues here.  I filed bug #6 to track that one.

So what is your use case here?  What ID are you searching by, and why do you need the result as a dict?

**Comment by Hellowlol** [comment]
i can see that my requests where written a bit hastily. 

1. Searching by id
2. It would be nice to have as_dict or raw where everything from plex Api is dumped as a list of dicts.

I would like to swap out the custom code in https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/plex.py and use your package instead

**Comment by mjs7231** [comment]
# I believe this is covered by pull request #5.
# Not sure this is worth adding as we'll always be chasing new keys and things added by Plex. This is is also already crudely available by using the __dict__ method on Python objects.

    from plexapi.server import PlexServer
    In [3]: plex = PlexServer()
    In [4]: naa = plex.library.section('TV Shows').get('Naked and Afraid')
    In [5]: naa.unwatched()[0]
    Out[5]: <Episode:Lord.of.the.Rats>
    In [6]: naa.unwatched()[0].__dict__
    Out[6]: 
    {'addedAt': datetime.datetime(2015, 6, 1, 1, 5, 5),
     'duration': 2553000,
     'grandparentTitle': 'Naked and Afraid',
     'index': '6',
     'initpath': '/library/metadata/2703/allLeaves',
     'key': '/library/metadata/17802',
     'originallyAvailableAt': datetime.datetime(2015, 5, 31, 0, 0),
     'parentIndex': '4',
     'parentKey': '/library/metadata/14926',
     'player': None,
     'ratingKey': '17802',
     'server': <PlexServer:localhost:32400>,
     'summary': "A workaholic mom and a loner are challenged to survive three weeks in Thailand. Competing with monkeys and rats for food, it's a daily struggle not only to survive, but to understand each other. Will they be able to come together as a team?",
     'thumb': '/library/metadata/17802/thumb/1433135136',
     'title': 'Lord of the Rats',
     'type': 'episode',
     'updatedAt': datetime.datetime(2015, 6, 1, 1, 5, 36),
     'user': None,
     'viewCount': 0,
     'viewOffset': 0,
     'year': 2015}
