### ISSUE TITLE
client.timeline hangs

### ISSUE THREAD

**Issue by miniconfig** [mjs7231/python-plexapi#22]
I'm not certain this is a bug and not bad coding on my part (apologies if it is the latter), but in my usage of python-plexapi I occasionally end up with a client sitting at the user/pin screen.  In this instance, if I try to access the timeline, it just seems to hang...shouldn't this connection attempt timeout?  I noticed the timeline definition doesn't pass the TIMEOUT value like other calls to requests.get do:
```
 def timeline(self):
        url = self.url('timeline/poll')
        params = {'wait':1, 'commandID':4}
        xml_text = requests.get(url, params=params, headers=BASE_HEADERS).text
        return ElementTree.fromstring(xml_text)
```

**Comment by mjs7231** [comment]
I think you're right, this should have a timeout, or go through the normal wrapper in place for requests.get.  I'll take a look at this as well when I return from vacation.

**Comment by mjs7231** [comment]
commit b2c9a29d1e0d9c0242a01f2e574292b7591dea8d
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sun Aug 30 20:59:25 2015 -0400
Update timeline() to use server.query to include proper headers and timeout.
