### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/python-plexapi#3]
```python
>>> rev = plex.library.get('Revenge')
>>> print(rev)
<Show:b'Revenge'>

>>> eps = rev.episodes()
>>> print(eps)
[<Episode:b'Pilot'>, <Episode:b'Trust'>]

>>> rev.searchEpisodes('Trust')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
```

I found this: http://stackoverflow.com/questions/3283441/python-nonetype-is-not-callable-error
but i couldnt find a `type = None` anywhere

Am I calling `searchEpisodes` incorrectly or is this a python bug?

**Comment by mjs7231** [comment]
Can you provide the full code snippet here?  This isn't really enough to know exactly what you were doing and what happened.

NoneType is not callable usually means you had a reference to None and tried using it as a function.  That would imply that `get` or `searchEpisodes` was somehow assigned to None.

**Comment by simonwjackson** [comment]
@mjs7231 updated the code snippet. Hope this helps.

**Comment by mjs7231** [comment]
This is actually an invalid bug.  It's confusing though. -- There is a difference between a "Show" and "ShowSection", and they work differently.

* ShowSection is a library of many shows and that contains the function search() and searchEpisodes().
* Show - This is an actual series title such as Revenge.  This contains the function episode(title) that you can use to get to a specific episode.

Searching only works at the Library level (I am not sure if Plex supports searching within a series).
