### ISSUE TITLE
Custom CONFIG path

### ISSUE THREAD

**Issue by pannal** [mjs7231/python-plexapi#31]
I'd love to try this library for https://github.com/pannal/Sub-Zero.bundle, but there seems to be no possibility to set the CONFIG stuff externally. I can't rely on any ~/.config stuff, because plugins in Plex are executed inside a sandbox.

**Comment by pannal** [comment]
... so defining a path for the config, better: even the possibility to override the config would help :)

**Comment by mjs7231** [comment]
The config file is just a convenient way to default a few settings. Everything the config file sets is easily accessible and able to be over-ridden in the plexapi.__init__ file. For example, you can set the default timeout by just setting `plexapi.TIMEOUT` to some other value.

```python
import plexapi
plexapi.TIMEOUT = 30
plexapi.X_PLEX_PLATFORM = 'my awesome app'
...continue...
```

PlexAPI is using the standard logging module. So you can easily set the log settings as you normally would in other Python projects even without the config file.

```python
import logging
from logging.handlers import RotatingFileHandler
plexlog = logging.getLogger('plexapi')
loghandler = RotatingFileHandler('/tmp/plexlog.log', 'a', 512000, 3)
plexlog.addHandler(loghandler)
...continue...
```

I just committed a small change that allows you to call a convenience function to reset the BASE_HEADERS if you want to change some of the X_PLEX header information. So you do something like this.

```python
import plexapi
plexapi.X_PLEX_DEVICE = 'My Awesome Windows Box'
plexapi.BASE_HEADERS = plexapi.reset_base_headers()
...continue...
```
