### ISSUE TITLE
Implement __eq__ or __cmp__ in plexapi/utils.py;NA 

### ISSUE THREAD

**Issue by pannal** [mjs7231/python-plexapi#32]
Being able to compare `utils.NA` to None or False would really help.

**Comment by mjs7231** [comment]
Can you explain the use case here a bit more? I specifically created NA instead of setting values to None. to help distinguish between a parsed and 'not yet' parsed media details.

**Comment by mjs7231** [comment]
commit 649dcf2cfd1142db98c34cfcf711604f6500327a
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Mar 14 00:19:48 2016 -0400
Implement __eq__ for NA; Test apostrophe in titles; Test fetching detailed metadata (using NA)
