### ISSUE TITLE
Add configurable Plex-Token instead of credentials

### ISSUE THREAD

**Issue by pannal** [mjs7231/python-plexapi#33]
It would be nice for external library usage to be able to set the Plex-Token externally in the config, not having to re-authenticate.

**Comment by mjs7231** [comment]
This has actually always been possible by using the PlexServer() object directly.

```python
from plexapi.server import PlexServer

baseuri = 'http://some_server:32400'
token = '123456'
plex = PlexServer(baseuri, token)
```

**Comment by mjs7231** [comment]
commit 36ed5cc833e8f4de78a9f0a83117446ce3e93465
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Mar 14 00:57:04 2016 -0400
Add docs to fetch PlexServer() without needing to log into MyPlex
Add this as an option in the tests and examples as well
