### ISSUE TITLE
Support for music

### ISSUE THREAD

**Issue by tomduijf** [mjs7231/python-plexapi#36]
Hi mjs,

Awesome work, keep it up!

So Plex music support happened ;)

I noticed plexapi doesnt support music media, only video with many types (show, movie, episode, season, etc). Fully understand it's not an easy feat to get music support in as nice as video.

Would love it if things like sessions do show a minimal set of info though. Right now it strictly handles video only (https://github.com/mjs7231/python-plexapi/blob/master/plexapi/server.py#L102)

**Comment by havardgulldahl** [comment]
Hey guys. Just wanted to let you know that I've started dabbling with music support in my tree https://github.com/havardgulldahl/python-plexapi 

I started out with just duplicating the video pipe in `video.py` and `server.py`. As of now, my changes don't interfere with anything, but I suggest that down the line we have to do some changes to merge video and audio handlnig.

If you are interested, @mjs7231, I'll submit a pull request to get the integration going. And, of course, please tell me if you want something done differently.

**Comment by mjs7231** [comment]
Sweet, from an initial glance it looks like it a great addition. Send the pull request and I can look at the diff a bit better. So far this project has been pretty lonely with contributors, so its also great to have such a contribution. Thanks.

I don't know much about Plex audio handling yet. What parts do you think need to be merged? -- In my initial thoughts it seems like a better idea to me to keep them separated. I could easily imagine a whole bunch of small paper-cut like differences between video/audio turning messy real quick if we merge without be too careful.

**Comment by tomduijf** [comment]
Plex handles has different library functions / contexts (artist, album, etc) for music like movies and series (show, season, etc).
python-plexapi integrates nicely on the library specific stuff for movies and series, makes sense to also do this for music.

**Comment by havardgulldahl** [comment]
Please take a look at https://github.com/mjs7231/python-plexapi/pull/41 and add your comments.

There is absolutely room for audio support integrated, the Plex API has this nicely separated. 

What I'm talking about is merging code paths and refactoring to avoid duplicated code. In #41,  `audio.py` is almost identical to `video.py`, duplicating a lot of stuff. Take a look, and you'll see :)

**Comment by mjs7231** [comment]
Just an update here. havardgulldahl code from #41 has been merged, but there is still a bit more work to do before I would say the API is settled down. Specifically, I want to unwind the common bits of the Audio and Video classes into a common location to share what we can.

**Comment by mjs7231** [comment]
Closing this one out.

commit a999df8e94991e3ad3218fd301ef2d4577d8eb76
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Mar 21 23:12:12 2016 -0400
Audio support complete; Added more audio tests; renamed is_watched to isWatched

**Comment by mjs7231** [comment]
@havardgulldahl Were you able to get the stream URL working for audio, or was it basically a port of the existing code?

**Comment by mjs7231** [comment]
Sorry nevermind.  VLC was wigging out because I didn't have quotes around that massive URL.

**Comment by mjs7231** [comment]
Bah, I'm noisy today.  I'm still having trouble getting this working for Albums and Playlists. It makes sense to be, but seems like what should be done is we loop through each item in the album or playlist and get the stream urls individually. But I'm a bit thrown off because it seems like work was put into adding the getStreamURL functions to Album and Playlist.

```
ERROR - TranscodeUniversalRequest: unexpected number of media items: 0
Mar 22, 2016 23:26:13 [0x7f71d67ff700] DEBUG - Completed: [127.0.0.1:53173] GET /video/:/transcode/universal/start.m3u8?path=%2Fplaylists%2F37119&mediaIndex=0 (10 live) 5ms 228 bytes 400
```

**Comment by Bart274** [comment]
so can we now see what music someone is playing etc?
can this be released on pypi?

**Comment by mjs7231** [comment]
Still a few weeks away from being updated on github.
