### ISSUE TITLE
add a function to parse results of api '/status/sessions/history/all'

### ISSUE THREAD

**Issue by mratsamy** [mjs7231/python-plexapi#42]
Can you add a function to parse the results of hitting http://localhost:32400/status/sessions/history/all?

Using your script right now. Would be nice to get a list of dictionaries with data like last video watched and the time

**Comment by Hellowlol** [comment]
You can do what with requests already just set the content type header to application/json and use r.json()

**Comment by mjs7231** [comment]
@Hellowlol - OMG, I have been hating using the XML view of the PlexAPI!

**Comment by Hellowlol** [comment]
Srsly? Lol. I just figured you used it since you like it better.

**Comment by mjs7231** [comment]
I wish, I started this project about a year and a half ago and documentation was super sparse then (not there there is a ton of documentation now).

**Comment by mjs7231** [comment]
It doesn't seem to be working for me.

```python
import plexapi, requests

plex = plexapi.server.PlexServer('http://HOST:32400', 'TOKEN')
url = plex.url('/status/sessions/history/all')
headers = plex.headers()
headers['Content-Type'] = 'application/json'
response = requests.get(url, headers=headers)
print(response.text)
```

Shouldn't I expect a json string to be printed there?

**Comment by Hellowlol** [comment]
Dunno how long it has worked but ive been using json since 15 Jan 2014. (It was broken but a did made a repair function)

**Comment by Hellowlol** [comment]
Sec, i have never tested that url, i have only used the other ones, i just figured it worked since every other i have tried has worked.

**Comment by Hellowlol** [comment]
Ah, sorry it was 'Accept': 'application/json'

**Comment by mjs7231** [comment]
Awesome, thanks!

**Comment by Hellowlol** [comment]
Im happy to help, its the least i can do. The api is beautiful :)

**Comment by mjs7231** [comment]
commit 80529a21c7230abc4dd41c3c7522702efc270c4e
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Apr 7 01:39:04 2016 -0400
Rename MyPlexUser to MyPlexAccount; Add support for real MyPlexUsers; Add api for history; New tests for sessions() and history()

**Comment by Hellowlol** [comment]
Any plans to add to add any query regarding the history?

@mratsamy if you want some simple watched stats you can find a simple script here: https://gist.github.com/Hellowlol/0047e27e2e17593b48ab708312956b71

**Comment by mjs7231** [comment]
I think that is slightly out of scope of what I wanted this package to do. Essentially I want to provide the ability to read and navigate what Plex is providing in their xml docs, but leave the 'build cool stuff on top of it' to everyone else. It's definetly worth an example or two though.

commit 81e22147c04e0344e63d3c466c726e947827e798
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Apr 7 22:48:45 2016 -0400
Get examples working again; Add new examples most_streamed_titles and most_active_users

As a side note. Do you know if we have any filter options on the history?  This history takes quite a while to load on my system with something like 10000+ items from all this testing. :open_mouth:

**Comment by Hellowlol** [comment]
Ok. Im afraid not.

**Comment by ovived** [comment]
how come i dont get json when i do this
