### ISSUE TITLE
Question how to do `unseen with actor "name"` queries

### ISSUE THREAD

**Issue by danielBreitlauch** [mjs7231/python-plexapi#43]
I try to do some searches like:
- unseen with actor "name" 
- unseen and R-rated

I figured to use the generic search method of a MovieSection `def search(self, title, filter='all', vtype=None, **tags)` with `actor=Name` tags and `filter='unwatched'`.
But the method expects an Actor object not a String.

Could you give an example how you would do it? I don't see the possibility to get the Actor object from a name String.

Btw great work and thanks for making it public.

**Comment by mjs7231** [comment]
At the time of writing this, I wasn't aware, or it wasn't available yet to search by actor.  It looks like it is available now to get a list of all actors then choose one from there. The url to fetch all actors is `https://<PLEX-SERVER>/library/sections/1/actor?type=1`. From there, you could get the actor resource ids needed to list all movies containing that actor.

All of this is not available in this API yet.

**Comment by dodegy** [comment]
Not sure if the python style is ok but I added the functionality in #44.

**Comment by mjs7231** [comment]
This can be closed now.

commit b10faf8560f19a5047bea5e0b117a1300ef5d58d
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Mar 31 16:52:48 2016 -0400
Checkpoint: New implementation for search
