### ISSUE TITLE
Empty Clients

### ISSUE THREAD

**Issue by character-not-found** [mjs7231/python-plexapi#45]
Hello there.

Thanks for this, it has been incredibly helpful.

However, the clients list (as specified in example 3) is empty, as I believe plex no longer has a '\clients' url. At least with both my PMP and mobile clients connected, that container is empty. I believe now this needs to be pulled from 'https://plex.tv/pms/resources'. Is this correct? If so, can the code be adjusted to that?

Thanks

**Comment by character-not-found** [comment]
I was mistaken. The firewall was blocking that information for some reason. Sorry

**Comment by iSkipp3r** [comment]
Oh my goodness...I'm so glad I found this...why in the world is a firewall blocking this? I've been stumped for hours.

**Comment by mjs7231** [comment]
lol, I think I'm hitting this as well now. Not sure whats going on as I have no firewall. What I am seeing sounds a bit like this thread: https://forums.plex.tv/discussion/144468/plex-companion-fling-option-missing-from-plex-web

Going to reopen this bug for now while I investigate.

**Comment by mjs7231** [comment]
OK, in my case.  For whatever reason GDM got disabled on my server. Simply re-enabling that got things working again: Settings > Server > Network > Enable local network discovery (GDM).
