### ISSUE TITLE
Support for Photos

### ISSUE THREAD

**Issue by blade2005** [mjs7231/python-plexapi#47]
I have a Music section and photos and I'm not getting those libraries. 

`<Directory allowSync="0" art="/:/resources/artist-fanart.jpg" composite="/library/sections/3/composite/1458279050" filters="1" refreshing="0" thumb="/:/resources/artist.png" key="3" type="artist" title="Music" agent="com.plexapp.agents.lastfm" scanner="Plex Music Scanner" language="en" uuid="ab1afce0-4f31-4fd5-845b-73add7bf6748" updatedAt="1458279050" createdAt="1387300385">
`
my sections only has my movie sections, 

no errors were generated in getting sections.

The output from http://localhost:32400/library/sections has those sections as shown by the above output.

`music = plex.library.section('Music')`
Fails with 
> plexapi.exceptions.NotFound: Invalid library section: Music

**Comment by mjs7231** [comment]
Audio and Photos are not implemented yet. -- That said Audio is about to be complete on the master branch and should be released to pip within a few weeks. I'll leave this bug open, but simply rename it to "Add support for Photos"

**Comment by blade2005** [comment]
Ah. I was confused because I saw what looked to be mostly complete support in master but wasn't looking at the pip release.  Now I just kinda feel stupid for not seeing the support for music issue. Thanks.

**Comment by mjs7231** [comment]
No need to feel stupid, there are too many places to look and miss minute details. Especially for an undocumented project like this one.

**Comment by mjs7231** [comment]
An update on this one. Audio was added a few weeks ago and seems to be working fine for me, but hasn't had much time in the hands of other people. I am adding support for Photos tonight and should have it in working order within a few days.

**Comment by mjs7231** [comment]
commit 09a7ae80db141539267a25a3c32ea9758a6f6292
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sat Apr 9 23:59:47 2016 -0400
Basic support for photos complete
