### ISSUE TITLE
Some objects are passing the incorrect key

### ISSUE THREAD

**Issue by mjs7231** [mjs7231/python-plexapi#50]
In some cases the Plex XML API's are passing a key of `/library/metadata/<key>/children` when in fact the key should really just be `/library/metadata/<key>` without the /children part at the end. This is causing problems in PlexPartialObject where it never thinks it has the full object, because we don't have the correct reference to the items main page. Currently we see this in the following objects from Plex.
- Audio Artist - requires self.key.replace('/children', '')
- Audio Album - requires self.key.replace('/children', '')
- Playlist - requires self.key.replace('/items', '')

To get around this, we added a flag for objects: `FIX_BUG_50` to note we are doing something weird to get around this issue.

**Comment by Hellowlol** [comment]
this also led to bugs when reloading the object would reload the child. fx season.reload(). I believe i have fixed this the responses branch. The test pass atleast.

**Comment by mjs7231** [comment]
Closing this one with the merged fix and added tests.

commit 6e761f0fc5bf026e5ef980a884f8e9e0f3a8af09
Merge: 5f9c230 e2efc5f
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Wed Feb 1 22:05:59 2017 -0500
Merge pull request #100 from Hellowlol/responses
Responses
