### ISSUE TITLE
How get a list of all audio albums?

### ISSUE THREAD

**Issue by beville** [mjs7231/python-plexapi#52]
Maybe I'm missing something, but I just can't figure out how to get a list all audio albums with this API.  The equivalent REST API path would be:
`/library/sections/<section_id>/albums`

I was trying to call "searchAlbums()" with no params, but that was raising an error:

```
  File "./api-test.py", line 84, in <module>
    main()
  File "./api-test.py", line 79, in main
    generate_playlist("cask.local", name, list_size)
  File "./api-test.py", line 41, in generate_playlist
    all_albums = music_section.searchAlbums()
  File "/usr/local/lib/python2.7/dist-packages/PlexAPI-2.0.0a_.................................._.version.of.this.api-py2.7.egg/plexapi/library.py", line 270, in searchAlbums
    return self.search(libtype='album', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PlexAPI-2.0.0a_.................................._.version.of.this.api-py2.7.egg/plexapi/library.py", line 193, in search
    if libtype is not None: args['type'] = utils.searchType(libtype)
  File "/usr/local/lib/python2.7/dist-packages/PlexAPI-2.0.0a_.................................._.version.of.this.api-py2.7.egg/plexapi/utils.py", line 261, in searchType
    if libtype in SEARCHTYPES + SEARCHTYPESSTRS:
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

**Comment by mjs7231** [comment]
I think it's an oversight. Audio support is very new and your probably the first person to really dig in. I'll make it work tomorrow.

**Comment by beville** [comment]
Cool, thanks for doing all this.  No need to rush on my account, I'm just playing around. :-)

I see now that the code is mostly video oriented.  I was also hoping to get a client object to "playMedia()" on an audio playlist, but looks like that won't work as implemented.  Something to keep in mind!

**Comment by mjs7231** [comment]
commit 1a679411dc1d8e3dab76b0344409f9bb50284e6d
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Tue Apr 12 22:47:46 2016 -0400
Ability to list all albums; Fix setting object values when not found (NA) and we know its the full object

**Comment by mjs7231** [comment]
commit c75db1df103f664e7417f06ebc6e54c2323e2651
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Tue Apr 12 22:55:45 2016 -0400
Fix broken utils.searchType()

**Comment by mjs7231** [comment]
Some things that still need to be done here:
* Create tests for audio playback.
* Ability to play playlists (or convert a playlist to a playqueue).

**Comment by beville** [comment]
Changes look great!

For what it's worth, here are some code snippets that I got to work for playing playlist on client:

Create PlayQueue:
```
        path = "/playQueues"
        path += "?playlistID={}".format(playlist_id)
        path += "&shuffle=0&type=audio&includeChapters=1&includeRelated=1"    
```

Start playqueue on client, using response from above:

```
    playqueue_selected_metadata_item_id = playqueue[u'playQueueSelectedMetadataItemID'] 
    playqueue_id = playqueue[u'playQueueID'] 

    # Tell the client to play the playlist
    url = "http://{}:{}/player/playback/playMedia".format(CLIENT_IP,CLIENT_PORT)
    url += "?key=%2Flibrary%2Fmetadata%2F{}".format(playqueue_selected_metadata_item_id)
    url += "&offset=0"
    #url += "&X-Plex-Client-Identifier={}".format(CLIENT_ID)
    url += "&machineIdentifier={}".format(SERVER_ID)
    url += "&address={}".format(server_ip)
    url += "&port={}".format(server_port)
    url += "&protocol=http"
    url += "&containerKey=%2FplayQueues%2F{}%3Fown%3D1%26window%3D200".format(playqueue_id)
    url += "&commandID=2"

```

**Comment by mjs7231** [comment]
Awesome, I should be able to get this in tonight. You're doing all the hard research, I love it!

**Comment by mjs7231** [comment]
commit 5701af7ed40bac952992820ee57706f037bd7e74
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Wed Apr 13 22:36:12 2016 -0400
Ability to play playlists
