### ISSUE TITLE
Support New Hub Search

### ISSUE THREAD

**Issue by mjs7231** [mjs7231/python-plexapi#53]
Yesterday a new PlexWeb version was released which included a new global search which is supper fast, forgiving and a bit more contextual. We should make sure the server.search() option is using this. Perhaps we can return results grouped in a dictionary or something.

![](https://3dvu3f3j4cnh2807drow35tb-wpengine.netdna-ssl.com/wp-content/uploads/2016/04/smart.gif)

**Comment by mjs7231** [comment]
Pull request #90 looks to be covering this.

**Comment by mjs7231** [comment]
This was merged and is working great!

**Comment by Hellowlol** [comment]
Seems it broke a lot of tests.

**Comment by mjs7231** [comment]
It did, I plan to look at that sooner than later.  I looked briefly last night and the error messages didn't make any sense to me so I went to bed. :D

**Comment by Hellowlol** [comment]
xD

**Comment by mjs7231** [comment]
Just commited a fix for the tests. A few of them were giving me datetimes that were 5 hours off, I assume because of timezone differences. We should probably convert all datetimes to timestamps in the tests before comparing.
