### ISSUE TITLE
Subsequent call to <show>.episodes() returning zero results.

### ISSUE THREAD

**Issue by edurand** [mjs7231/python-plexapi#56]
Hello, 
Thanks for putting the API together. 
These two commands return very different results: 
```python
plex.library.get('Game of Thrones').episodes()
Out[49]: 
[<Episode:The.Red.Woman>,
 <Episode:Home>,
 <Episode:Oathbreaker>,
 <Episode:Book.of.the.Stranger>]
```
vs.
```python
got = plex.library.get('Game of Thrones')
got.episodes()
Out[53]: []
```
How come?

**Comment by mjs7231** [comment]
That looks odd to me as well. I'll take a look tonight. In the mean time, you should get better results by getting the library section first and not searching directly from the top level library.

**Comment by mjs7231** [comment]
The library.get(title) function checks `/library/all` and iterates all the items looking for the title specified. I generally find this this page returned from Plex doesn't contain everything that you may expect. I added it in the API simply because Plex has it as well. 

The better way to get results is to go into the section first to get the actual `Show` object then navigate around that. Take a look at the following example:

```python
plex = PlexServer()
tvshows = plex.library.section('TV Shows')
got = <Show:1762/allLeaves:b'All.episodes'>
got.episodes()

[<Episode:1764:b'Winter.Is.Coming'>,
 <Episode:1765:b'The.Kingsroad'>,
 <Episode:1766:b'Lord.Snow'>,
 ...,
]
```

**Comment by mjs7231** [comment]
Going to reopen this as a todo item to remove the bad examples from the readme.

**Comment by edurand** [comment]
Actually, I'm still seeing a fairly strange behavior going through the TV Shows section; if I query twice, the second time returns empty results. 
```
plex = PlexServer()
In [87]: tvshows = plex.library.section('TV Shows')
In [88]: got = tvshows.get('Game of Thrones')
In [89]: got.episodes()
Out[89]: 
[<Episode:The.Red.Woman>,
 <Episode:Home>,
 <Episode:Oathbreaker>,
 <Episode:Book.of.the.Stranger>]
In [90]: got.episodes()
Out[90]: []
```

**Comment by mjs7231** [comment]
This one is not happening to me in iPython or on the cmd line. I ran the example just as posted in the above comment but get the expected results every time. Is there some weird caching thing going on with your iPython or something?

**Comment by mjs7231** [comment]
Closing this bug as it's only an issue in iPython.
