### ISSUE TITLE
Recently added is missing from LibrarySection

### ISSUE THREAD

**Issue by logaritmisk** [mjs7231/python-plexapi#58]
It seems recentlyAdded is missing from LibrarySection. Is that deprecated? Should I use Library.recentlyAdded instead?

**Comment by logaritmisk** [comment]
It disappeared in commit b10faf8560f19a5047bea5e0b117a1300ef5d58d

**Comment by mjs7231** [comment]
Plex web no longer uses the api url that function used in favor of Search with an order by date added. I'll provide an example tonight. 

Perhaps it's worth keeping that function in this library but having it call search instead of the url it used to call?

**Comment by logaritmisk** [comment]
Ah, I see. I think it might be an good idea to keep it, but mark it as deprecated for a while

**Comment by mjs7231** [comment]
commit 3d28b5309e67e38759911224d34718d599740ce9
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon May 23 21:41:02 2016 -0400
Recently added is missing from LibrarySection #58
