### ISSUE TITLE
timeline / isMediaPlaying giving parse error

### ISSUE THREAD

**Issue by amazingr4b** [mjs7231/python-plexapi#59]
When trying to use the timeline and isMediaPlaying options I get the following parse error:  
requests.exceptions.InvalidURL: Failed to parse: 192-168-1-134.longstingoflettersnumberhere.plex.direct:32400timeline  

I'm trying it as follows from a python console:  
from plexapi.myplex import MyPlexUser
user = MyPlexUser.signin(PLEXUN, PLEXPW)
plex = user.getResource(PLEXSVR).connect()
client = plex.client(CLIENT)
client.isPlayingMedia()
(OR)
client.timeline()

and then I get the above error. 
Am I doing something wrong to cause that parse error?

**Comment by mjs7231** [comment]
Thanks for the bug. Looks like there is a missing slash before the word `timeline` in the url. Are you using the version from pip or the most current version from github?

**Comment by amazingr4b** [comment]
I have been using the version off pip.

**Comment by mjs7231** [comment]
I think this bug may be invalid then. I'll retest the current master to double check before closing the bug.  A new version of this library should hit pip within a week or two.

There are a few api changes, but you are welcome to try this version in your project if you're OK with a few changes before I release to pip.

```bash
pip install -U git+git://github.com/mjs7231/python-plexapi.git
```

**Comment by amazingr4b** [comment]
Thanks for the followup. I'll give that version a try tonight.

**Comment by amazingr4b** [comment]
Using that version I was able to successfully use both actions. Thanks again for the followup.

**Comment by amazingr4b** [comment]
Is it possible to add in the isMediaPlaying function a second condition so paused content is not treated the same as stopped? I now use this to determine when something is playing vs stopped, and I don't want to react to paused content like it were stopped. In my local copy I the following to that function:
elif mediatype.get('state') == 'paused':
                return True

Thought others might want to use it the same way and might find that useful.

**Comment by mjs7231** [comment]
Seems reasonable.

commit 0c8587ceac3186767ac06681ef7372d8e43e85a5
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon May 23 19:33:56 2016 -0400
Option to include paused content when requesting is media is playing.
