### ISSUE TITLE
Document ability to playmedia action with offset

### ISSUE THREAD

**Issue by amazingr4b** [mjs7231/python-plexapi#60]
I noticed the remote control API was updated and mentions that the play media action now supports the offset argument. Is it possible to get that support added here? I find it would be nice to be able to resume something from where you left off, should the need arise.

I added a line to the setParameters function for it, and it works for me:
if offset is not None: params['offSet'] = offset # offset value in ms

**Comment by mjs7231** [comment]
I assume you are talking about the `plexapi.client.Client.playMedia()` function?  You should be able to do this already by simply adding the additional keyword when calling the function.

```python
client.playMedia(<some_media>, offset=1234)
```

**Comment by amazingr4b** [comment]
Cool that does already work. When I was trying it earlier I had been using 'offSet' instead of 'offset,' and then added some extra usless crap that I didn't needed to. Thanks for pointing that out.

**Comment by mjs7231** [comment]
I'll leave the bug open because this should be documented in the code.

**Comment by mjs7231** [comment]
commit 0aac1156a14a7b6a1ece2763dbc0bc5543fd668c
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Feb 2 01:32:38 2017 -0500
Add offset as optional playMedia() argument; Document it
Clenaup old tests as its the only way to test client actions right now
