### ISSUE TITLE
Several APIs returning invalid URLs

### ISSUE THREAD

**Issue by abcminiuser** [mjs7231/python-plexapi#64]
There are several APIs such as the `thumbUrl` propery of `Video` which return a URL, using an object that may or may not have been fetched at the time of the request:

https://github.com/mjs7231/python-plexapi/blob/master/plexapi/video.py#L261

This results in the URL being combined from the Plex base URL, plus a `_NA` object stringified, giving an invalid URL such as `http://127.0.0.1:32400/__NA__`. I think it's more reasonable to return either a `None` or `_NA` object in these cases.

**Comment by mjs7231** [comment]
Definitely a bug, thanks for reporting it. I'll see if I can look tonight.

**Comment by abcminiuser** [comment]
Great! I was going to just make a PR for the obvious case, but thought you might have a better handle on where else it might be popping up in the API surface.

On the subject of music media thumbnails, is there value trying to pick the least distant non-NA thumbnail? Right now it uses the grandparent thumbnail (album, or artist?) but some of my media has only track thumbnails, artist thumbnails or album thumbnails. Picking the closest thumbnail in the hierarchy might be better than always punting to the same upper level.

If you're looking for real world uses of this API, check out the Home-Assistant project 🙂.

**Comment by mjs7231** [comment]
Added new bug for the track thumbnail issue:
Choose Closest Thumbnail for Audio Tracks #102

**Comment by Hellowlol** [comment]
I think i have fixed the issue with __NA__ being apart of the url.

**Comment by mjs7231** [comment]
Fix looks good to me.
