### ISSUE TITLE
PlexServer() no longer working

### ISSUE THREAD

**Issue by edurand** [mjs7231/python-plexapi#68]
Hi, 

I was using plexapi successfully for a while and then moved to a new place, havent touched it in a while. 

Now I can no longer connect to plex server using plexapi.server.PlexServer. I get the following error:

```
In [1]: from plexapi.server import PlexServer

In [2]: ps = PlexServer()
---------------------------------------------------------------------------
NotFound                                  Traceback (most recent call last)
<ipython-input-2-553a4ba3c216> in <module>()
----> 1 ps = PlexServer()

/Users/eric/miniconda3/envs/plex/lib/python2.7/site-packages/plexapi/server.pyc in __init__(self, baseurl, token, session)
     25         self.token = token
     26         self.session = session or requests.Session()
---> 27         data = self._connect()
     28         self.friendlyName = data.attrib.get('friendlyName')
     29         self.machineIdentifier = data.attrib.get('machineIdentifier')

/Users/eric/miniconda3/envs/plex/lib/python2.7/site-packages/plexapi/server.pyc in _connect(self)
     48         except Exception as err:
     49             log.error('%s: %s', self.baseurl, err)
---> 50             raise NotFound('No server found at: %s' % self.baseurl)
     51
     52     @property

NotFound: No server found at: http://localhost:32400
```

Note however that if I'm using the MyPlexAccount method, it works. Interestingly, _after_ I create an account with MyPlexAccount, connect through the account, then plex=PlexServer() works fine.  

Any idea/suggestion? 

I'm using plexapi 2.0.2 with python 2.7

Thanks!

**Comment by amazingr4b** [comment]
If you are trying to use the local access, it looks like you are missing some arguments. I use it as follows:  

token = "tokengoeshere"
url = "serverurlgoerhere"
plex = PlexServer(url, token)

**Comment by edurand** [comment]
Thanks, I will try that as well. However, PlexServer() with no argument used to work, and it's still referred in the tutorial. 

Was there a change from Plex then? If it's deprecated, then the tutorial should reflect this.

**Comment by mjs7231** [comment]
edurand is right in that the following code snippet used to work.  I haven't had a chance to test it yet to see if Plex changed something or not. The scary part is that you say it works *after* first connecting with a username and pass?

```In [1]: from plexapi.server import PlexServer
In [2]: ps = PlexServer()```

**Comment by edurand** [comment]
Yes, it does work *after* connecting first with passwd.

**Comment by mjs7231** [comment]
For what it's worth, its not working for me either as edurand explained. They must now require a username and password to connect locally.  I'll have to update the documentation accordingly.

**Comment by amazingr4b** [comment]
Did you try adding your local network as an allowed network without authorization? I had to make use of that option some months ago when they added it to keep it working in my setup.

**Comment by edurand** [comment]
Is that a new Plex setting?

**Comment by amazingr4b** [comment]
Been around for at least a few months. You'd have to check the plex sever changelog to see when it happened.

**Comment by mjs7231** [comment]
Closing this one. As far as I can tell you can't access the API urls anymore without specifying an auth token, which is what was required to use `plexapi.server.PlexServer()` without any credentials. I tried messing around with the "List of IP addresses and networks that are allowed without auth" option in the server settings, but nothing seemed to be working for me.

Reopen if you feel I should research this more.
