### ISSUE TITLE
Get the URL to stream a video

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/python-plexapi#7]

**Comment by mjs7231** [comment]
I'm curious about this request. How are you using this url?  I assumed it would only be useful with a proper plea client.

**Comment by simonwjackson** [comment]
The response of the URL is a video stream that you can simply pass to VLC, MPV or many other video players.

**Comment by simonwjackson** [comment]
@mjs7231 Looking into it a bit further, the stream is: h264, aac

I'm guessing this is because X-Plex-Platform is set to chrome

**Comment by mjs7231** [comment]
NOTE: With commit 43e99e94 you can now specify the headers including X-Plex-Platform via an ini file.

**Comment by mjs7231** [comment]
I can't get this to stream in VLC, not sure what I'm doing wrong here. :(

**Comment by simonwjackson** [comment]
@mjs7231 Can you paste the URL? (feel free to scrub the IP) :smiley:

**Comment by mjs7231** [comment]
Here is the URL I am trying to load into VLC: 

    http://localhost:32400/video/:/transcode/universal/start?maxVideoBitrate=128&X-Plex-Platform=Chrome&copyts=1&offset=0&path=http%3A%2F%2F127.0.0.1%3A32400%2Flibrary%2Fmetadata%2F%2Flibrary%2Fmetadata%2F4431&mediaIndex=0&videoResolution=1280x720

**Comment by mjs7231** [comment]
I added this without using a separate StreamURL object. The function Video.getStreamURL was added using your code as the example, thanks!

commit 527b0ee
Author: Michael Shepanski mjs7231@gmail.com
Date: Thu Jun 4 00:00:37 2015 -0400
Add Video.getStreamURL()

**Comment by simonwjackson** [comment]
My only concern is that a `Series` or a `Show` object now contains a method called `getStreamURL` which gives an invalid URL.

Should the code be restructured to account for this?

**Comment by ZePaiva** [comment]
Is this method still available on Movie objects or has it passed to otther type of objects?

If it's still available on Movie objects what is the code to get it?
I'm using this sample but it's throwing AttributeError:
```python
server=PlexServer( ( HOST+':'+str(PORT) ), PLEX_TOKEN)
mov=server.library.section('Movies').get('mov1')
print(mov.getStreamUrl())
```

**Comment by blacktwin** [comment]
@ZePaiva Method is still working. Please provide more information like the entire error. Also create a new issue or use the Python-PlexAPI Discord.
