### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by postables** [mjs7231/python-plexapi#72]
I'm finding it hard to figure out what exactly this API Can do, other than the examples listed in README.md, I'm finding it pretty difficult to explore the different options.

At this point what I'm doing consists of using help() to try and figure what each object/method can do. This doesn't really seem "scalable" and is fairly time consuming.

Is there a readthedocs webpage or something?

**Comment by mjs7231** [comment]
Unfortunately, not yet.  I never had the time to put into better docs. :(

**Comment by postables** [comment]
No worries, that's understandable as it would require a significant portion of time to do so.

Thanks for the response

**Comment by mjs7231** [comment]
A lot of work was already put in by @Hellowlol for this.  I also started another branch to take that work and format it for Sphinx documentation after which we'll get this up on ReadTheDocs. I suspect this will take a few weeks to fully clean things up.

**Comment by Hellowlol** [comment]
Can't we use the extension  Napoleon with spinx? I choose google docs style since that is the most human readable.

**Comment by mjs7231** [comment]
Of course, I was hoping you would chime in. I never used Spinx before, don't know much about it or the best approach.

**Comment by Hellowlol** [comment]
Afraid i dont know anything about it. Never used it but im sure we can figure it out.

**Comment by mjs7231** [comment]
We should use Napoleon to parse the google docstyle to rst to it passes this to sphinx before building docs. I choose google docs style because imo its the most readable docstring type. Changing this to rst manually would make the docs harder to read and would be a huge task.

extensions = ['sphinx.ext.autodoc', 'sphinxcontrib.napoleon']
See http://sphinxcontrib-napoleon.readthedocs.io/en/latest/

**Comment by mjs7231** [comment]
This is getting there (slowly). I'll be out of town this weekend, but expect to finish reviewing and adding to everything next week at which time we can look into publishing to Read The Docs. After this is done, I'd love to look into the new test suite and get that running cleaning on TravisCI. @Hellowlol, you did an amazing first pass on this, thanks so much!

A few guidelines I was following to make it a bit easier.
* No need to document dunder functions (\_\_init__, \_\_repr__, etc).
* No need to over-document private methods (_functions).

Completed: Audio, Client, Config, Exceptions, Library, MyPlex, Utils
Remaining: Media, Photo, Playlist, Playqueue, Server, Sync, Video

**Comment by Hellowlol** [comment]
Awesome stuff. How are you solving this?. Are you editing adding the classes manually.? Or using some kind of tool? . I don't know why i didn't add proper classes in the first go. Anyway thank you so much.

**Comment by mjs7231** [comment]
Closing this one.  There is still some work to do for docs, but we're well on our way and its part of the build system now!

http://python-plexapi.readthedocs.io/en/latest/?badge=latest
