### ISSUE TITLE
getting error on clients

### ISSUE THREAD

**Issue by chrillep** [mjs7231/python-plexapi#74]
plexapi/server.py", line 65, in clients
    baseurl = 'http://%s:%s' % (elem.attrib['address'], elem.attrib['port'])
KeyError: 'address'

changing it to elem.attrib['host'] works

**Comment by mjs7231** [comment]
Hmm, this is working fine for me. My server is returning the same value in both `host` and `address` in the returned XML. I'm changing this to `host`, but I have no idea why your server was missing the `address` attribute.

commit 16a55316f1892be42a878162413bd8e8875334c8
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Feb 2 01:42:12 2017 -0500
Bug #74 - getting error on clients
