### ISSUE TITLE
Stream Playlist to a client via URL

### ISSUE THREAD

**Issue by foxy82** [mjs7231/python-plexapi#79]
Hi,

I'm trying to stream a playlist to a client via a url but when I do:

playlist.getStreamURL()

I get an error:
plexapi.exceptions.Unsupported: Fetching stream URL for playlist is unsupported.

How can I stream a playlist like this?

Thanks.

**Comment by mjs7231** [comment]
This has been a common request recently. I'll see if I can get together a good example shortly.

**Comment by Hellowlol** [comment]
I dont understand. Are you trying to play a playlist on something like VLC or your mobile phone?

**Comment by mjs7231** [comment]
Ohh, I misunderstood the question. The getStreamURL() is not supported for a playlist, only single media elements. The exception you are seeing is hard coded into the API to explicitly state that.

**Comment by foxy82** [comment]
Well I was thinking of trying to push it to a Chromecast... However I might
be able to implement what I need iterating through the tracks.
