### ISSUE TITLE
Get Season/Episode by plex_index

### ISSUE THREAD

**Issue by jasonlyle88** [mjs7231/python-plexapi#85]
# Proposal #
It would be really useful to be able to get a season or episode via the plex index number (aka, season and episode number).

For example, I need to lookup Season 3 Episode 5 of some show.

As of right now, I get the `Show` and then I have to use the `season()` method with a parameter of `"Season 3"` (name of the season). Once I have that season, I have to use the `episodes()` method and loop through the results to find the episode with an index of 5.  I am unable to use the `episode()` method because it looks up the episode by title, not episode index.

So what I propose is that once I get the series, i can call a method (for example) `get_season_by_number(3)` on the show and it will return the 3rd season.  If season 3 does not exist, then throw a `KeyError` or return `None`.  Next, i can call a method (for example) `get_episode_by_number(5)` on the season and it will return the 5th episode.  If episode 5 does not exist, then throw a KeyError or return None.

While what currently exists is one of the main ways to do a lookup, I believe the method I mentioned is a rather crucial lookup as well.

# Side Note #

Better naming of the  `season()` and `episode()` methods may also be something to look into for the future as well.  `get_season_by_name()` and `get_episode_by_name()` would be more self documenting.  Simply marking the `season()` and `episode()` as deprecated, and having the deprecated methods call `get_season_by_name()` and `get_episode_by_name()`, respectively, would be a great leap forward in usability.  This could also be applied to the `get()` methods of the `Show` class and `Season` class

**Comment by Hellowlol** [comment]
I dont see the isssue. I like the seasons and episodes. It would've be easy to add a wrapping that handles this for you. Parsing the xml is sequence so you could always do seasons()[4] to get the fifth season. Same goes for episodes.

**Comment by jasonlyle88** [comment]
Looking up seasons and episodes via number by using the array index number on the `seasons()` and `episodes()` method's return value was my first thought as well.  However, it is a flawed concept. Using `seasons()[4]` will only return the 5th season if all previous seasons are already there.

Lets say you have seasons 1, 2, 3, 5, 6, and 7.  A call to `seasons()[0]` returns Season 1.  So i assumed that this worked.  However, on further testing, I noticed that a call to `seasons()[4]` returns Season 6, not season 5.  Since season 4 is missing, that throws off getting the season or episode by number if anything is missing.

Essentially, I am trying to write a script that searches for missing episodes by using this tool you have provided (thanks!) and the pytvdbapi and seeing if anything present from tvdb (that has also already aired) is missing from plex.

And you are right, I can absolutely write a wrapper for it.  I just thought it would be a useful addition to this API.  I figure I can't be the only one wanting to look up season and episode by their number.

**Comment by Hellowlol** [comment]
Good point. I'm a digital hamster so nothing is missing :p. But seriously using a tool like sonarr or sickrage/medusa/ etc would probably be easier as they can check this and auto download anything missing.

Write a wrapper add it to it utils or add it to the show class or overload _getattr__ and send a pr. Maybe @mjs7231 would like you solution and accept the pr.

**Comment by mjs7231** [comment]
I like the idea, but do we need new function?  We could easily see if you passed `season()` a an integer and react to that appropriately and then default back to the current behavior for all non-integer values.

**Comment by Hellowlol** [comment]
@mjs7231 Rember that a episode title could be a int. Should it be passed as it?

**Comment by mjs7231** [comment]
I think that would be ok, but maybe a bit confusing. If an episode is titled 23 but is actually s01e05. They could get the episode by calling `episide('23')` or `episode(5)`.

**Comment by amazingr4b** [comment]
I say you can already do this with what is provided. 

I do something like this to determine what a specific episode is by season and episode number when I want to pay things that way:

the_show = shows.get(show).episodes()
for iep in the_show:
	if ((int(iep.seasonNumber) == int(Ssn)) and (int(iep.index) == int(Epnum))):
		ep = str(iep.title)

I'm sure its the most effective way to do it, but it works for my use case, which is to play a specific episode on demand by season and episode number. If the given season/episode doesn't exist in my library it tosses an error. As far as I can tell having gaps in your collection doesn't throw off the season/episode numbers, you just cant play items you don't have, obviously.

**Comment by mjs7231** [comment]
Thanks @amazingr4b, that looks like pretty much exactly what this should be, just built into the the API as it seems like a very common use case.

**Comment by Hellowlol** [comment]
https://github.com/mjs7231/python-plexapi/pull/91

**Comment by mjs7231** [comment]
This was merged into master 2 weeks ago.
