### ISSUE TITLE
Add Automated Testing (and more tests)

### ISSUE THREAD

**Issue by mjs7231** [mjs7231/python-plexapi#92]
We current have 5 broken test (out of a total of 46 tests). We should fix these.

```
test_navigation.py:6:# TODO: test_navigation/test_navigate_to_movie
test_navigation.py:27:# TODO: Fix test_navigation/test_navigate_around_show
test_playlists.py:14:# TODO: Fix test_playlists/test_create_playlist
test_search.py:79:# TODO: Fix test_search/test_crazy_search
test_sync.py:5:# TODO: Fix test_sync/test_sync_items
```

**Comment by Hellowlol** [comment]
I took the libery starting to port out tests to pytest. My goal is that we should be able to automate any test that don't interact with a client via Travis on each pr. The tests you have written is very clean so will be easy to adapt them to pytest (thanks!) at the same time I'll fix the rest you have listed here.

If it's any interesting you can track my progress there https://github.com/Hellowlol/plexapi/tree/responses

**Comment by mjs7231** [comment]
This is great.  I'm worried about all these branches already.  Feel like I should merge the sphinx stuff in already since it's not really affecting much and we can get docs progressively better as we move forward.

**Comment by Hellowlol** [comment]
So my initial plan blowed up.. Testing was well under way but i was testing against im own library. Only the responses from pms was over 150mb... I have added a droplet and make a test account for plex. Im gonna send you a friends later. I know nothing about linux so it might take a while xD

**Comment by mjs7231** [comment]
Is this on a Digital Ocean node? We should also look into adding Travis CI next? I have a Travis page here, but never used it myself.  I'll figure it out this week or so. -- https://travis-ci.org/mjs7231/python-plexapi

**Comment by Hellowlol** [comment]
Yes, its running in a Cheap droplet

**Comment by mjs7231** [comment]
I got the first test passing in Python 2.7 and Python 3.5 on Travis CI. I'd love to make the rest work. Things we need.

* A more extensive library of movies.
* Configuration for test movie, shows, etc. I'm not sure if we can drop a configuration file on Travis CI, but we could easily put those into environment variables as well. See variables below.
* A way to test client interactions.  Maybe we can spin up a second Digital Ocean image running Gnome or something with Plex Home Theater on it.  Or maybe we omit client and playback testing for now.

```ini
[testing]
show_section = TV Shows
show_title = Game of Thrones
show_season = Season 1
show_episode = Winter Is Coming
movie_section = Movies
movie_title = Jurassic World
movie_foreign = Bedside Detective
audio_section = Music
audio_artist = Beastie Boys
audio_album = Licensed To Ill
audio_track = Brass Monkey
photo_section = Photos
photo_album = 2015-12-12 - Family Photo for Christmas card
client = pkkid-home
client_baseurl = http://192.168.1.131:3005
```

**Comment by mjs7231** [comment]
Possibly worth a try, but Travis may be able to install PHT itself.

http://craigthomas.ca/blog/2014/05/26/travis-ci-and-gui-testing/
https://docs.travis-ci.com/user/installing-dependencies/

**Comment by Hellowlol** [comment]
I have like 60 test or so that passes to so far. :) I suggest we drop client for now. You can run the tests I'll send you the token, username and password to the account. I intent to test everything so we cache regression bugs.

**Comment by mjs7231** [comment]
This is awesome, I'm excited. :man_dancing:

**Comment by Hellowlol** [comment]
I sent you a mail now. If i ever get enough linux skills ill give you access to the droplet too. There is atleast be 1 tests that fail. I did that on purpose to i know where i was :P

**Comment by Hellowlol** [comment]
So we have 64 passing tests atm. The pr is starting to get huge. I wanted to add hub and write tests to this to but ill hold off until this is merged.

**Comment by mjs7231** [comment]
Closing! We have automated testing now! Thanks so much for the work on this! :+1:
