### ISSUE TITLE
PlexServer Instance error in examples

### ISSUE THREAD

**Issue by ourcontact** [mjs7231/python-plexapi#96]
Seems to be error on https://pypi.python.org/pypi/PlexAPI/2.0.2

Example given:
from plexapi.server import MyPlexAccount
baseurl = 'http://plexserver:32400'
token = '2ffLuB84dqLswk9skLos'
plex = PlexServer(baseurl, token)

seems like it should be:
from plexapi.server import PlexServer
baseurl = 'http://plexserver:32400'
token = '2ffLuB84dqLswk9skLos'
plex = PlexServer(baseurl, token)

**Comment by Hellowlol** [comment]
Thanks! The correct example should be

from plexapi.myplex import MyPlexAccount
account = MyPlexAccount.signin('<USERNAME>', '<PASSWORD>')
plex = account.resource('<SERVERNAME>').connect()  

if you want to login via the plex account.

**Comment by mjs7231** [comment]
This will be fixed on the next push to pypi. That may be several weeks though, I'd love to get documentation on ReadTheDocs and automated testing on Travis CI complete before the next release.

**Comment by mjs7231** [comment]
Closing this one as it's technically fixed, just not on pypi yet.
